name: Multi-arch Docker Build (GHCR)

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write  # 推送镜像到 GHCR 需要此权限

jobs:
  build:
    runs-on: ubuntu-latest  # 必须在 Linux 环境下运行

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU (支持多平台仿真)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx (启用多平台构建)
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
          driver-opts: |
            network=host  # 提升构建速度

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push (多平台镜像)
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7  # 指定目标平台
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/myapp:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/myapp:latest
