name: Multi-arch Docker Build (GHCR)

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write  # 推送镜像到 GHCR 需要此权限

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # 关键修复步骤 1: 启用 QEMU（支持 ARM 构建）
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 关键修复步骤 2: 使用 `docker-container` 驱动
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container 
          driver-opts: |
            network=host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push (多平台镜像)
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7 
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/myapp:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/myapp:latest
